num1=int(input("enter numeber1 "))
num2=int(input("enter number2 "))
num3=int(input("enter number3 "))
print (num1 + num2 + num3)
person=input("name: ")
print (person)
number=input("num1 ")
number2=input("num2 ")
print(number>number2)
word=input("word ")
nnum=int(input("number "))
print(word * nnum)
nnumber1=input("nnumber1 ")
nnumber2=input("nnumber2 ")
print(int(nnumber1 + nnumber2) + 1)